name: Deploy to AWS S3

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ruby-full build-essential zlib1g-dev
          gem install bundler jekyll --user-install --install-dir /home/runner/.gem
          export PATH="/home/runner/.gem/bin:$PATH"
          echo "/home/runner/.gem/bin" >> $GITHUB_PATH
      - name: Build site
        run: |
          bundle config set path vendor/bundle
         bundle install
          bundle exec jekyll build
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync _site/ s3://mikemalburg.com --delete && aws s3api put-bucket-policy --bucket mikemalburg.com --policy file://s3-policy.json
