name: Deploy to AWS S3
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby dependencies
        run: |
          sudo apt-get install ruby-full build-essential zlib1g-dev -y
          gem install --user-install jekyll bundler
          echo "$HOME/.gem/ruby/3.2.0/bin" >> $GITHUB_PATH
      - name: Build site
        run: bundle exec jekyll build
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync _site/ s3://mikemalburg.com --delete && aws s3api put-bucket-policy --bucket mikemalburg.com --policy file://s3-policy.json
